# Name of your site
name: Vorpal Dice Press
# Short bio or description
description: Test site for Vorpal Dice Press
# your name/username
author: Steve Fidler
contact_email: vorpaldicepress@gmail.com

# Your website URL. Used for Sitemap.xml and your RSS feed
url: https://vorpal.borntodostuff.com
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# If you're hosting your site at a Project repository on GitHub pages (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io) then add in the baseurl here, like this: "/repository-name"
#baseurl: ""

#collections:
#  type:
#    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: product
    values:
      layout: blog
      permalink: /blog/:title/
      title: Blog Post

collections:
  products:
    output: true
    permalink: /product/:title/
    sort_by: release_date
    title: New Product
    layout: product
  reviews:
    output: true
    permalink: /review/:title/
    title: New Review
    layout: review


excerpt_separator: "<!--excerpt-->"
excerpt_length: 150

permalink: /:title/
paginate: 10
paginate_path: "/page/:num/"

# The release of Jekyll Now that you're using
version: v3.7.3

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  parse_block_html: true

sass:
  style: :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
